
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 266730739760-10nk3cc439ih1nsapt3kb4mrgmarfgpk.apps.googleusercontent.com
            client-secret: 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
